services:
  registry: ghcr.io/cassamajor
  tag: v0.9.9-gh
  frontend: 
    image: frontend-go
  agenda: 
    image: agenda-service
  c4p: 
    image: c4p-service
  notifications: 
    image: notifications-service
install:
  infrastructure: true
  ingress: true
postgresql:
  image:
    debug: true
  primary: 
    persistence:
      size: "1Gi"
    initdb:
      user: postgres
      password: postgres
      scriptsConfigMap: c4p-init-sql
  global:
    postgresql:
      auth: 
        postgresPassword: postgres
redis: 
  architecture: standalone
  master:
    persistence:
      size: "1Gi"
kafka: 
  persistence:
    size: "1Gi"
  provisioning:
    topics:
    - name: events-topic
      partitions: 1