services:
  registry: ghcr.io/cassamajor
  tag: v0.9.9-gh
  frontend: 
    image: frontend-go
    annotations:
      omni-kube-service-exposer.sidero.dev/port: "50083"
      omni-kube-service-exposer.sidero.dev/label: Frontend
  agenda:
    image: agenda-service
    annotations:
      omni-kube-service-exposer.sidero.dev/port: "50084"
      omni-kube-service-exposer.sidero.dev/label: Agenda
  c4p:
    image: c4p-service
    annotations:
      omni-kube-service-exposer.sidero.dev/port: "50085"
      omni-kube-service-exposer.sidero.dev/label: Call For Proposals
  notifications:
    image: notifications-service
    annotations:
      omni-kube-service-exposer.sidero.dev/port: "50086"
      omni-kube-service-exposer.sidero.dev/label: Notifications

install:
  infrastructure: true
  ingress: true
postgresql:
  image:
    debug: true
  primary: 
    persistence:
      size: "1Gi"
    initdb:
      user: postgres
      password: postgres
      scriptsConfigMap: c4p-init-sql
  global:
    postgresql:
      auth: 
        postgresPassword: postgres
redis: 
  architecture: standalone
  master:
    persistence:
      size: "1Gi"
kafka: 
  persistence:
    size: "1Gi"
  provisioning:
    topics:
    - name: events-topic
      partitions: 1