name: Frontend Service - Service Pipeline

on:
  push:
    branches: ['main']

jobs:
  publish:
    name: Frontend Service - Service Pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          check-latest: true
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - 'conference-application/frontend-go/**'

      - if: steps.changes.outputs.src == 'true'
        uses: ko-build/setup-ko@v0.6

      - if: steps.changes.outputs.src == 'true'
        run: cd conference-application/frontend-go && ko build -t v0.9.9-gh --base-import-paths # https://ko.build/configuration/#naming-images